---
# tasks file for role
#

- name: Deploy /etc/hosts file from template
  ansible.builtin.template:
    src: templates/etc/hosts.j2
    dest: /etc/hosts
  tags: [ hostsfile ]
  when: hostsfile is defined

